### ISSUE TITLE
"NODE_ENV=production node_modules/.bin/webpack -p" produce no bundle.js file

### ISSUE THREAD

**Issue by dagman** [lmammino/judo-heroes#4]
I am working through your amazing article building every js file step by step and finally i have reached this line: "NODE_ENV=production node_modules/.bin/webpack -p".
I have added npm script like this:
 "scripts": {
    "build": "NODE_ENV=production node_modules/.bin/webpack -p"
  }
and get returned an error. And smart guys whispered me that as soon as i am on windows i should prepend script with "set" so i changed it to:
 "build": "set NODE_ENV=production node_modules/.bin/webpack -p"

Now i got no errors but no bundle.js file is produced. Simply nothing.
Please help me to figure this out.

**Comment by BeHiz** [comment]
I'm having the same issue on windows 10.
I did solve the problem by running set 
`NODE_ENV=production` 
and then, as a separate command 
`node_modules/.bin/babel-node --presets 'react,es2015' src/server.js`

**Comment by pailhead** [comment]
try doing something like

    "start": "set NODE_ENV=production&&webpack -p"

include `&&`

**Comment by cskonopka** [comment]
Same issue from the git and the website tutorial, blank page when everything is said and done. Seems to be a bundle issue but don't know how to go about it. Please help, this is a great tutorial!

**Comment by EduardJS** [comment]
Hei :) Not sure what you did here on other systems but I had to replace the "build" property with "postinstall", as the "build" command just wouldn't run.

Note that I am deplying on Heroku, so it may not apply to you guys.

**Comment by lmammino** [comment]
@EduardJS did you run `npm build` or `npm run build` (the latter is the correct one, I know it's always confusing... 😝 )

**Comment by lmammino** [comment]
Just added support for multi-os env variables using [cross-env](https://www.npmjs.com/package/cross-env) module.

**Comment by EduardJS** [comment]
@lmammino I am deploying onto Heroku, using nodejs buildpack. Therefore the running command is "npm start". 

And since heroku has a "postinstall" utility for `package.json` I figured I would just use that instead.
Not sure if there's anything to do, as I didn't bother searching for a fix anyway.

Don't think there's anything to do about that anyway!
