### ISSUE TITLE
How to get this working with SCSS?

### ISSUE THREAD

**Issue by robertwbradford** [lmammino/judo-heroes#5]
Thanks for the great tutorial and sample app. I've been working on a project that uses webpack's `css-loader` and `style-loader`. Things work fine for the development server, however, when running `npm run start` it looks like Babel doesn't know what to do about `import`ing the SCSS or CSS files. This isn't a problem with your application, but I'm wondering if you have any ideas. 

So I have a `Layout` component in `~/source/components/layout/layout.jsx`:

```jsx
import React from 'react';
import styles from './layout.scss';

export default class Layout extends React.Component {
  render() {
    return (
      <div className={styles.layout}>
        <h1>You Got the Layout!</h1>
        <main className={styles.main}>{this.props.children}</main>
      </div>
    );
  }
}
```

Notice it is importing the SCSS from `./layout.scss`. However, when I run `start` I get the following:

```
$ npm run start
> NODE_ENV=production node_modules/.bin/babel-node source/server.js

~/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

SyntaxError: ~/source/components/layout/layout.scss: Unexpected token (1:0)
> 1 | .layout {
    | ^
  2 |   background-color:dodgerblue;
  3 |   padding: 1em;
  4 |   color: white;
    at Parser.pp$5.raise (~/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp.unexpected (~/node_modules/babylon/lib/index.js:1627:8)
    at Parser.pp$3.parseExprAtom (~/node_modules/babylon/lib/index.js:3586:12)
    at Parser.parseExprAtom (~node_modules/babylon/lib/index.js:6402:22)
    at Parser.pp$3.parseExprSubscripts (~/node_modules/babylon/lib/index.js:3331:19)
    at Parser.pp$3.parseMaybeUnary (~/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (~/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (~/node_modules/babylon/lib/index.js:3218:19)
    at Parser.pp$3.parseMaybeAssign (~/node_modules/babylon/lib/index.js:3181:19)
    at Parser.parseMaybeAssign (~/node_modules/babylon/lib/index.js:5694:20)

```

I've seen the `ignore` option for Babel, but couldn't get it to work, and it looks like there are some issues with it anyway.

I've also seen https://github.com/webpack/webpack/issues/1754.

In other projects I've seen that webpack is run first, but I'm not getting how to do this with your express setup.

If anyone has any ideas, please let me know. Thanks.

**Comment by Rob-Leggett** [comment]
+1

**Comment by lmammino** [comment]
Hello @robertwbradford and @Rob-Leggett,
I haven't tried this approach honestly, but I think the solution lies in using a webpack loader for sass files.

You can check out [this tutorial](https://medium.com/@Connorelsea/using-sass-with-create-react-app-7125d6913760#.4guiqu9mh) as a reference.

I am closing this for now but feel free to write a comment here if the tutorial doesn't help you to sort out the issue. I will take care of finding a proper solution then.

Regards and thanks for opening this interesting discussion. 

PS: also these other links can help:

- https://webpack.github.io/docs/loaders.html
- https://github.com/jtangelder/sass-loader
