### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by realtebo** [lmammino/judo-heroes#8]
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check your code at routes.js:10.

This is my routes.js file 

```
import React from 'react'
import { Route, IndexRoute } from 'react-router'
import Layout from './components/Layout';
import IndexPage from './components/IndexPage';
import AthletePage from './components/AthletePage';
import NotFoundPage from './components/NotFoundPage';

const routes = (
  <Route path="/" component={Layout}>
    <IndexRoute component={IndexPage}/>
    <Route path="athlete/:id" component={AthletePage}/>
    <Route path="*" component={NotFoundPage}/>
  </Route>
);

export default routes;
```

Row 10 is:

```
<IndexRoute component={IndexPage}/>
```

And this is IndePage component source

```
import React, { Component } from 'react';
import AthletePreview from './AthletePreview';
import athletes from '../data/athletes';

export default class IndexPage extends Component {
  render() {
    return (
      <div className="home">
        <div className="athletes-selector">
          {athletes.map(athleteData => <AthletePreview key={athleteData.id} {...athleteData} />)}
        </div>
      </div>
    );
  }
}

```

really, I've  no idea of what am I doing wrong.

**Comment by lmammino** [comment]
At a first glance, the code you showed me looks correct. Did you also had a look at the other components like `Layout` to be sure you are correctly exporting all of them?

I look forward to hearing from you

**Comment by lmammino** [comment]
Hey @realtebo, I hope you managed to find the issue. Since I cannot replicate your issue I am closing this for now, but feel free to come back to me with more details or a complete example I can checkout and I'll be happy to reopen this if needed.
