### ISSUE TITLE
Data on Client or Server?

### ISSUE THREAD

**Issue by joshuaquek** [lmammino/judo-heroes#9]
Hello,

Thank you for taking the time to read this.

I'm just curious, 

Does the code for **judo-heroes/src/data/athletes.js** exist on the client or on the server?

If I replace those codes with data gotten from MongoDB, would my mongo codes be exposed on the client side?

Also, since this app is isomorphic/universal, I can simply use mongoDB from the client side? Or must I still call the REST endpoints from the frontend? (It's not recommended to use JQuery's AJAX anymore with React right?)

Hope to hear from you soon!

**Comment by lmammino** [comment]
Hello @joshuaquek,
first of all thanks for having a look at the code in this repo.

Regarding your question, the code in that file gets bundles both in the server code and in the client code.

Anyway if you want to expose this data through a database you will need to create an API that will be called by both the client and the server (depending on the lifecycle of the current request). This approach will ensure that the data in the DB can be consumed only through a well-defined interface (your REST API) and thus it will expose only the data that can be consumed by a client.

On the second part of the question, you can use the tools/library you prefer to do AJAX calls (including jQuery), but take into account that to achieve universal data retrieval (ability to call APIs seamlessly from both the client and the server) you will need a library with this capability like [axios](https://github.com/mzabriskie/axios) or [universal-fetch](https://github.com/Pitzcarraldo/universal-fetch).

I am closing this one now, hoping that my response was satisfying enough, but feel free to reply again if you want more details or to open a new Issue if you have other questions.

Also have a look at [V2 of this repository](https://github.com/lmammino/judo-heroes-2) and to [Fullstack Bulletin](https://fullstackbulletin.com/), a free and open source weekly newsletter about FullStack web development I recently launched, I hope it will be interesting for you :).
